version: "3.9"

services:
  db:
    restart: unless-stopped
    image: "postgres"
    container_name: db
    environment:
      POSTGRES_PASSWORD: dsadsa
      POSTGRES_USER : super
    ports:
      - "5432:5432"


  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"

